### ISSUE TITLE
Still some problem with cluster - no cluster.xml found

### ISSUE THREAD

**Issue by lukjel** [vert-x3/vertx-openshift-cartridge#3]
I saw your update - thx for it.

I removed and recreat demo app.

However my "demo" app is not working in cluster env.

I removed from my project cluster.xml. I expect cluster.xml generated by cartridge will be used. Currently - there will be just one node... 

When pushed changes I see this:

```
remote: CLIENT_MESSAGE: Vert.x OPTS:  -Dhttp.port=8080 -Dhttp.address=127.7.180.129 -Dvertx.cluster.public.host=10.145.206.45 -Dvertx.cluster.public.port=52758
remote: CLIENT_MESSAGE: Vert.x Cluster parameters : -cluster -cluster-port 9123 -cluster-host 127.7.180.129
remote: CLIENT_MESSAGE: Vert.x Application parameter : -cp /var/lib/openshift/558936214382eca4690000b1/vertx//conf/cluster.xml:/var/lib/openshift/558936214382eca4690000b1/vertx//conf
```

(is this ok - double / before conf directory in -cp parameters? )

App is starting and then I see on console log this:

```
Jun 23, 2015 7:09:01 AM com.hazelcast.config.AbstractXmlConfigHelper
WARNING: Name of the hazelcast schema location incorrect using default
Jun 23, 2015 7:09:02 AM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [dev] [3.5] Prefer IPv4 stack is true.
Jun 23, 2015 7:09:12 AM com.hazelcast.instance.DefaultAddressPicker
SEVERE: [LOCAL] [dev] [3.5] ServerSocket bind has failed. Hazelcast cannot start! config-port: 5701, latest-port: 15701
com.hazelcast.core.HazelcastException: ServerSocket bind has failed. Hazelcast cannot start! config-port: 5701, latest-port: 15701
    at com.hazelcast.instance.DefaultAddressPicker.pickAddress(DefaultAddressPicker.java:117)
    at com.hazelcast.instance.Node.<init>(Node.java:143)
    at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:120)
    at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:152)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:135)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111)
    at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
    at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager.lambda$join$13(HazelcastClusterManager.java:100)
    at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager$$Lambda$3/13741961.handle(Unknown Source)
    at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:279)
    at io.vertx.core.impl.ContextImpl$$Lambda$5/24264240.run(Unknown Source)
    at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$199(OrderedExecutorFactory.java:91)
    at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor$$Lambda$4/13444057.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Permission denied
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:437)
    at sun.nio.ch.Net.bind(Net.java:429)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at com.hazelcast.instance.DefaultAddressPicker.pickAddress(DefaultAddressPicker.java:98)
    ... 15 more

2015-06-23 07:09:12,106 DEBUG Using default SystemClock for timestamps
07:09:12.116 [vert.x-eventloop-thread-0] ERROR io.vertx.core.impl.VertxImpl - Failed to join cluster
com.hazelcast.core.HazelcastException: ServerSocket bind has failed. Hazelcast cannot start! config-port: 5701, latest-port: 15701
    at com.hazelcast.instance.DefaultAddressPicker.pickAddress(DefaultAddressPicker.java:117) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at com.hazelcast.instance.Node.<init>(Node.java:143) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:120) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:152) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:135) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager.lambda$join$13(HazelcastClusterManager.java:100) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager$$Lambda$3/13741961.handle(Unknown Source) ~[?:?]
    at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:279) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at io.vertx.core.impl.ContextImpl$$Lambda$5/24264240.run(Unknown Source) ~[?:?]
    at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$199(OrderedExecutorFactory.java:91) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor$$Lambda$4/13444057.run(Unknown Source) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_45]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.net.SocketException: Permission denied
    at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_45]
    at sun.nio.ch.Net.bind(Net.java:437) ~[?:1.8.0_45]
    at sun.nio.ch.Net.bind(Net.java:429) ~[?:1.8.0_45]
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_45]
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_45]
    at com.hazelcast.instance.DefaultAddressPicker.pickAddress(DefaultAddressPicker.java:98) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    ... 15 more
07:09:12.143 [vert.x-eventloop-thread-0] ERROR com.git.ServerStarter -  ######################## error
```

and more...

So - it looks like Hazelcast can not find cluster.xml from cartridge (first line):

```
Jun 23, 2015 7:09:01 AM com.hazelcast.config.AbstractXmlConfigHelper
WARNING: Name of the hazelcast schema location incorrect using default
```

any idea?

**Comment by cescoffier** [comment]
No it won't use the cartridge `cluster.xml`, because it's created while installing the application. That's why you need to recreate your application.

**Comment by lukjel** [comment]
that was what I've got after recreate...

**Comment by lukjel** [comment]
To be clear. I made

```
rhc app delete demo
```

and then

```
rhc create-app demo https://raw.githubusercontent.com/vert-x3/vertx-openshift-cartridge/master/metadata/manifest.yml -s
```

I edited `vertx.env` from `configuration` directory (enable cluster - uncomment last line).
Copied new `demo*-fat.jar` to `application`
`git add -A; git commit -m "Some comment"; git push`
`rhc tail demo -o "-n 200"`
And I saw error as mentioned above... 
I've just repeated this again a few seconds ago with the same result.
I've also checked a file cluster.xml from conf directory (added to classpath) and it looks ok.
So I copied that file to my project and inserted to fat.jar
Now error messages are little different:

```
Jun 23, 2015 10:37:58 AM com.hazelcast.config.AbstractXmlConfigHelper
WARNING: Name of the hazelcast schema location incorrect using default
Jun 23, 2015 10:37:59 AM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [dev] [3.5] Picking address configured by property 'hazelcast.local.localAddress'
Jun 23, 2015 10:37:59 AM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [dev] [3.5] Picked Address[127.13.13.1]:36437, using socket ServerSocket[addr=/127.13.13.1,localport=36437], bind any local is false
Jun 23, 2015 10:37:59 AM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [dev] [3.5] Using public address: Address[10.63.68.238]:36437
Jun 23, 2015 10:37:59 AM com.hazelcast.spi.OperationService
INFO: [10.63.68.238]:36437 [dev] [3.5] Backpressure is disabled
Jun 23, 2015 10:37:59 AM com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor
INFO: [10.63.68.238]:36437 [dev] [3.5] Starting with 2 generic operation threads and 4 partition operation threads.
Jun 23, 2015 10:38:00 AM com.hazelcast.system
INFO: [10.63.68.238]:36437 [dev] [3.5] Hazelcast 3.5 (20150617 - 4270dc6) starting at Address[10.63.68.238]:36437
Jun 23, 2015 10:38:00 AM com.hazelcast.system
INFO: [10.63.68.238]:36437 [dev] [3.5] Copyright (c) 2008-2015, Hazelcast, Inc. All Rights Reserved.
Jun 23, 2015 10:38:00 AM com.hazelcast.instance.Node
INFO: [10.63.68.238]:36437 [dev] [3.5] Creating TcpIpJoiner
Jun 23, 2015 10:38:00 AM com.hazelcast.core.LifecycleService
INFO: [10.63.68.238]:36437 [dev] [3.5] Address[10.63.68.238]:36437 is STARTING
Jun 23, 2015 10:38:01 AM com.hazelcast.cluster.impl.TcpIpJoiner
INFO: [10.63.68.238]:36437 [dev] [3.5] 


Members [1] {
    Member [10.63.68.238]:36437 this
}

Jun 23, 2015 10:38:01 AM com.hazelcast.core.LifecycleService
INFO: [10.63.68.238]:36437 [dev] [3.5] Address[10.63.68.238]:36437 is STARTED
2015-06-23 10:38:04,374 DEBUG Using default SystemClock for timestamps
10:38:04.423 [vertx-blocked-thread-checker] WARN  io.vertx.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2736 ms, time limit is 2000
10:38:04.508 [vert.x-eventloop-thread-0] ERROR com.git.ServerStarter -  ######################## error
java.net.SocketException: Permission denied
    at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_45]
    at sun.nio.ch.Net.bind(Net.java:437) ~[?:1.8.0_45]
    at sun.nio.ch.Net.bind(Net.java:429) ~[?:1.8.0_45]
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_45]
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_45]
    at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:485) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1089) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:430) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:415) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:903) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:198) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:348) ~[demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357) [demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [demo-openshift-0.0.1-SNAPSHOT-fat.jar:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

And here are deploy parameters (received during `git push`):

```
remote: CLIENT_MESSAGE: Stopping Vert.x application
remote: Syncing git content to other proxy gears
remote: Building git ref 'master', commit 6497557
remote: Preparing build for deployment
remote: Deployment id is 89441be7
remote: Activating deployment
remote: HAProxy already running
remote: HAProxy instance is started
remote: Starting Vert.x application
remote: CLIENT_MESSAGE: Vert.x OPTS:  -Dhttp.port=8080 -Dhttp.address=127.13.13.1 -Dvertx.cluster.public.host=10.63.68.238 -Dvertx.cluster.public.port=36438
remote: CLIENT_MESSAGE: Vert.x Cluster parameters : -cluster -cluster-port 9123 -cluster-host 127.13.13.1
remote: CLIENT_MESSAGE: Vert.x Application parameter : -cp /var/lib/openshift/55896d385973ca119000021f/vertx//conf/cluster.xml:/var/lib/openshift/55896d385973ca119000021f/vertx//conf
remote: -------------------------
remote: Git Post-Receive Result: success
remote: Activation status: success
remote: Deployment completed with status: success
```

and here is `cluster.xml`:

```
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-basic.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <properties>
    <property name="hazelcast.mancenter.enabled">false</property>
    <property name="hazelcast.memcache.enabled">false</property>
    <property name="hazelcast.rest.enabled">false</property>
    <property name="hazelcast.wait.seconds.before.join">0</property>
    <property name="hazelcast.logging.type">jdk</property>
    <property name="hazelcast.local.localAddress">127.13.13.1</property>
    <property name="hazelcast.socket.server.bind.any">false</property>
    <property name="hazelcast.socket.client.bind">false</property>
  </properties>
  <group>
    <name>dev</name>
    <password>dev-pass</password>
  </group>
  <management-center enabled="false">http://localhost:8080/mancenter</management-center>
  <network>
    <public-address>10.63.68.238:36437</public-address>
    <port auto-increment="false" port-count="100">36437</port>
    <join>
      <multicast enabled="false">
        <multicast-group>224.2.2.3</multicast-group>
        <multicast-port>54327</multicast-port>
      </multicast>
      <tcp-ip enabled="true">
        <members>10.63.68.238:36437</members>
      </tcp-ip>
      <aws enabled="false">
        <access-key>my-access-key</access-key>
        <secret-key>my-secret-key</secret-key>
        <!--optional, default is us-east-1 -->
        <region>us-west-1</region>
        <!--optional, default is ec2.amazonaws.com. If set, region shouldn't be set as it will override this property -->
        <host-header>ec2.amazonaws.com</host-header>
        <!-- optional, only instances belonging to this group will be discovered, default will try all running instances -->
        <security-group-name>hazelcast-sg</security-group-name>
        <tag-key>type</tag-key>
        <tag-value>hz-nodes</tag-value>
      </aws>
    </join>
    <symmetric-encryption enabled="false">
      <!--
         encryption algorithm such as
         DES/ECB/PKCS5Padding,
         PBEWithMD5AndDES,
         AES/CBC/PKCS5Padding,
         Blowfish,
         DESede
      -->
      <algorithm>PBEWithMD5AndDES</algorithm>
      <!-- salt value to use when generating the secret key -->
      <salt>thesalt</salt>
      <!-- pass phrase to use when generating the secret key -->
      <password>thepass</password>
      <!-- iteration count to use when generating the secret key -->
      <iteration-count>19</iteration-count>
    </symmetric-encryption>
  </network>
  <partition-group enabled="false"/>
  <executor-service name="default">
    <pool-size>16</pool-size>

    <!-- Queue capacity. 0 means Integer.MAX_VALUE. -->
    <queue-capacity>0</queue-capacity>
  </executor-service>
  <map name="subs">
    <!--
      Number of backups. If 1 is set as the backup-count for example,
      then all entries of the map will be copied to another JVM for
      fail-safety. 0 means no backup.
    -->
    <backup-count>1</backup-count>
    <!--
      Maximum number of seconds for each entry to stay in the map. Entries that are
      older than <time-to-live-seconds> and not updated for <time-to-live-seconds>
      will get automatically evicted from the map.
      Any integer between 0 and Integer.MAX_VALUE. 0 means infinite. Default is 0.
    -->
    <time-to-live-seconds>0</time-to-live-seconds>
    <!--
      Maximum number of seconds for each entry to stay idle in the map. Entries that are
      idle(not touched) for more than <max-idle-seconds> will get
      automatically evicted from the map. Entry is touched if get, put or containsKey is called.
      Any integer between 0 and Integer.MAX_VALUE. 0 means infinite. Default is 0.
    -->
    <max-idle-seconds>0</max-idle-seconds>
    <!--
      Valid values are:
      NONE (no eviction),
      LRU (Least Recently Used),
      LFU (Least Frequently Used).
      NONE is the default.
    -->
    <eviction-policy>NONE</eviction-policy>
    <!--
      Maximum size of the map. When max size is reached,
      map is evicted based on the policy defined.
      Any integer between 0 and Integer.MAX_VALUE. 0 means
      Integer.MAX_VALUE. Default is 0.
    -->
    <max-size policy="PER_NODE">0</max-size>
    <!--
      When max. size is reached, specified percentage of
      the map will be evicted. Any integer between 0 and 100.
      If 25 is set for example, 25% of the entries will
      get evicted.
    -->
    <eviction-percentage>25</eviction-percentage>
    <!--
      While recovering from split-brain (network partitioning),
      map entries in the small cluster will merge into the bigger cluster
      based on the policy set here. When an entry merge into the
      cluster, there might an existing entry with the same key already.
      Values of these entries might be different for that same key.
      Which value should be set for the key? Conflict is resolved by
      the policy set here. Default policy is PutIfAbsentMapMergePolicy

      There are built-in merge policies such as
      com.hazelcast.map.merge.PassThroughMergePolicy; entry will be added if there is no existing entry for the key.
      com.hazelcast.map.merge.PutIfAbsentMapMergePolicy ; entry will be added if the merging entry doesn't exist in the cluster.
      com.hazelcast.map.merge.HigherHitsMapMergePolicy ; entry with the higher hits wins.
      com.hazelcast.map.merge.LatestUpdateMapMergePolicy ; entry with the latest update wins.
    -->
    <merge-policy>com.hazelcast.map.merge.LatestUpdateMapMergePolicy</merge-policy>
  </map>
</hazelcast>
```

**Comment by cescoffier** [comment]
just one question. Are you creating a HTTP server ? 

If so, you need to listen on `http.port`, `http.address`, as in https://github.com/vert-x3/vertx-examples/blob/master/openshift-example/src/main/java/io/vertx/example/HelloWorldVerticle.java#L11

**Comment by lukjel** [comment]
Yes. Right - this is what I'm doing. 
Please notice - not-cluster version is working properly.
The `################ error` log with PermissionDenied is logged here:
https://github.com/lzeligowski/vertx3-demo-openshift/blob/master/src/main/java/com/git/ServerStarter.java
(when there is a fail with starting clustered vertx).

Here is my server verticle code:
https://github.com/lzeligowski/vertx3-demo-openshift/blob/master/src/main/java/com/git/ServerVerticle.java

**Comment by cescoffier** [comment]
Oh, but you create your own vert.x. So you need to pass cluster-host and cluster-port.

**Comment by lukjel** [comment]
Ok. See the point.
How should I deploy my verticles? (without starting my own vertx instance).

**Comment by cescoffier** [comment]
Just create a `MainVerticle` deploying the other verticles. The vertx instance is created by the Vert.x starter.

**Comment by lukjel** [comment]
And is he looking for MainVerticle class? Is this a normal Verticle (extends AbstractVerticle)? Should it be in some specific package?

**Comment by cescoffier** [comment]
Yes it's a regular verticle, you just update the _fat jar_ creation with the fully qualified class name. 

If you are using Maven look at:
https://github.com/vert-x3/vertx-examples/tree/master/maven-verticle

There is a property indicating the main verticle class name.

**Comment by lukjel** [comment]
That's right.

stupid thing...

Rly thank you. Now it works :D
